# Generated by Django 5.1.1 on 2024-10-20 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OAuthProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("GOOGLE", "Google"), ("APPLE", "Apple")],
                        db_comment="OAuth를 제공하는 플랫폼 이름: GOOGLE, APPLE",
                        help_text="OAuth를 제공하는 플랫폼 이름: GOOGLE, APPLE",
                        max_length=10,
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        db_comment="플랫폼 내에서의 식별자",
                        help_text="플랫폼 내에서의 식별자",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        db_comment="User profile",
                        help_text="User profile",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oauth_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "OAuth Profile",
                "verbose_name_plural": "OAuth Profiles",
                "db_table": "oauth_profile",
                "db_table_comment": "OAuth profile",
                "ordering": ["id"],
                "unique_together": {("provider", "identifier")},
            },
        ),
    ]
