# Generated by Django 5.1.1 on 2024-11-03 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_oauthprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthprofile',
            name='user',
            field=models.ForeignKey(db_comment='User profile', help_text='User profile', on_delete=django.db.models.deletion.CASCADE, related_name='oauth_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
