# Generated by Django 5.1.1 on 2024-11-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_oauthprofile_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthprofile',
            name='provider',
            field=models.CharField(choices=[('google', 'Google'), ('apple', 'Apple')], db_comment='OAuth를 제공하는 플랫폼 이름: GOOGLE, APPLE', help_text='OAuth를 제공하는 플랫폼 이름: GOOGLE, APPLE', max_length=10),
        ),
    ]
