# Generated by Django 5.1.1 on 2025-02-03 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_oauthprofile_provider'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
