# Generated by Django 5.1.1 on 2025-02-08 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_user_managers_remove_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='oauthprofile',
            table='account_oauth_profile',
        ),
    ]
