# Generated by Django 5.1.1 on 2025-02-08 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_oauthprofile_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthprofile',
            name='provider',
            field=models.CharField(choices=[('google', 'Google'), ('apple', 'Apple')], db_comment='OAuth를 제공하는 플랫폼 이름: google, apple', help_text='OAuth를 제공하는 플랫폼 이름: google, apple', max_length=10),
        ),
    ]
