# Generated by Django 5.1.1 on 2024-11-03 03:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_comment='스케쥴 제목', help_text='스케쥴 제목', max_length=200)),
                ('content', models.TextField(blank=True, db_comment='스케쥴 내용', help_text='스케쥴 내용', null=True)),
                ('start_time', models.DateTimeField(db_comment='시작 시간', db_index=True, help_text='시작 시간')),
                ('end_time', models.DateTimeField(db_comment='종료 시간', db_index=True, help_text='종료 시간')),
                ('owner', models.ForeignKey(db_comment='스케쥴 소유자', help_text='스케쥴 소유자', on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedules',
                'db_table': 'schedule_schedule',
                'db_table_comment': 'Schedules',
                'ordering': ['id'],
            },
        ),
    ]
