# Generated by Django 5.1.1 on 2024-11-03 13:05

import caldal.util.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_comment='스케쥴 그룹 이름', help_text='스케쥴 그룹 이름', max_length=100)),
                ('color', models.CharField(blank=True, db_comment='스케쥴 표시에 사용되는 색의 HEX 코드', help_text='스케쥴 표시에 사용되는 색의 HEX 코드', max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='올바른 HEX 컬러 코드를 입력하세요', regex='^#([A-Fa-f0-9]{6})$')])),
                ('order_index', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('created_at', caldal.util.fields.CreatedAtField(auto_now_add=True, db_comment='생성 시간', help_text='생성 시간')),
                ('owner', models.ForeignKey(db_comment='스케쥴 그룹 소유자', help_text='스케쥴 그룹 소유자', on_delete=django.db.models.deletion.CASCADE, related_name='schedule_groups', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'ScheduleGroup',
                'verbose_name_plural': 'ScheduleGroups',
                'db_table': 'schedule_group',
                'db_table_comment': '스케쥴 그룹',
                'ordering': ['owner', 'order_index'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_comment='스케쥴 제목', help_text='스케쥴 제목', max_length=200)),
                ('content', models.TextField(blank=True, db_comment='스케쥴 내용', help_text='스케쥴 내용', null=True)),
                ('start_time', models.DateTimeField(db_comment='시작 시간', db_index=True, help_text='시작 시간')),
                ('end_time', models.DateTimeField(db_comment='종료 시간', db_index=True, help_text='종료 시간')),
                ('created_at', models.DateTimeField()),
                ('owner', models.ForeignKey(db_comment='스케쥴 소유자', help_text='스케쥴 소유자', on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('group', models.ForeignKey(db_comment='스케쥴 그룹', help_text='스케쥴 그룹', on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='schedule.schedulegroup', verbose_name='Group')),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedules',
                'db_table': 'schedule_schedule',
                'db_table_comment': 'Schedules',
                'ordering': ['owner', 'start_time'],
            },
        ),
    ]
