# Generated by Django 5.1.1 on 2024-11-05 12:05

import caldal.util.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='created_at',
            field=caldal.util.fields.CreatedAtField(auto_now_add=True, db_comment='생성 시간', help_text='생성 시간'),
        ),
    ]
