# Generated by Django 5.1.1 on 2024-11-07 13:02

import caldal.util.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_schedule_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulegroup',
            name='is_default',
            field=models.BooleanField(blank=True, db_comment='디폴트 여부', default=False, help_text='디폴트 여부'),
        ),
        migrations.AlterField(
            model_name='schedulegroup',
            name='order_index',
            field=caldal.util.fields.OrderIndexField(blank=True, db_index=True, default=0),
        ),
    ]
