# Generated by Django 5.1.1 on 2024-11-10 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_schedulegroup_is_default_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='is_all_day',
            field=models.BooleanField(db_comment='종일 이벤트인지 나타내는 값. 종일 이벤트의 경우 end_time이 null.', default=False, help_text='종일 이벤트인지 나타내는 값'),
        ),
    ]
