# Generated by Django 5.1.1 on 2024-11-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_schedule_is_all_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='timezone',
            field=models.CharField(db_comment='시간대. ex) Asia/Seoul', default='Asia/Seoul', help_text='시간대. ex) Asia/Seoul', max_length=35),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='is_all_day',
            field=models.BooleanField(db_comment='종일 이벤트인지 나타내는 값', default=False, help_text='종일 이벤트인지 나타내는 값'),
        ),
    ]
