# Generated by Django 5.1.1 on 2025-01-26 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_schedule_timezone_alter_schedule_is_all_day'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
