# Generated by Django 5.1.1 on 2025-01-30 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_delete_schedule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScheduleGroup',
        ),
    ]
