# Generated by Django 5.1.1 on 2025-02-03 11:20

import caldal.util.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule', '0007_delete_schedulegroup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField()),
                ('name', models.CharField(db_comment='스케쥴 그룹 이름', help_text='스케쥴 그룹 이름', max_length=100)),
                ('color', models.CharField(blank=True, db_comment='스케쥴 표시에 사용되는 색의 HEX 코드', help_text='스케쥴 표시에 사용되는 색의 HEX 코드', max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='올바른 HEX 컬러 코드를 입력하세요', regex='^#([A-Fa-f0-9]{6})$')])),
                ('is_default', models.BooleanField(blank=True, db_comment='디폴트 여부', default=False, help_text='디폴트 여부')),
                ('order_index', caldal.util.fields.OrderIndexField(blank=True, db_index=True, default=0)),
                ('created_at', caldal.util.fields.CreatedAtField(auto_now_add=True, db_comment='생성 시간', help_text='생성 시간')),
                ('updated_at', caldal.util.fields.UpdatedAtField(auto_now=True, db_comment='편집 시간', help_text='편집 시간', null=True)),
                ('owner', models.ForeignKey(db_comment='스케쥴 그룹 소유자', help_text='스케쥴 그룹 소유자', on_delete=django.db.models.deletion.CASCADE, related_name='event_groups', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'db_table': 'schedule_event_group',
                'db_table_comment': '이벤트 그룹',
                'ordering': ['owner', 'order_index'],
                'unique_together': {('owner', 'uuid')},
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField()),
                ('type', models.CharField(choices=[('RANGED', '범위 이벤트'), ('ALL_DAY', '하루종일 이벤트')], db_comment='이벤트 유형: RANGED(범위), ALL_DAY(하루종일)', default='RANGED', help_text='이벤트 유형: RANGED(범위), ALL_DAY(하루종일)', max_length=10)),
                ('title', models.CharField(db_comment='스케쥴 제목', help_text='스케쥴 제목', max_length=200)),
                ('content', models.TextField(blank=True, db_comment='스케쥴 내용', help_text='스케쥴 내용', null=True)),
                ('start_time', models.DateTimeField(db_comment='시작 시간', db_index=True, help_text='시작 시간')),
                ('end_time', models.DateTimeField(db_comment='종료 시간', db_index=True, help_text='종료 시간')),
                ('timezone', models.CharField(blank=True, db_comment='시간대. ex) Asia/Seoul', default='Asia/Seoul', help_text='시간대. ex) Asia/Seoul', max_length=35)),
                ('created_at', caldal.util.fields.CreatedAtField(auto_now_add=True, db_comment='생성 시간', help_text='생성 시간')),
                ('updated_at', caldal.util.fields.UpdatedAtField(auto_now=True, db_comment='편집 시간', help_text='편집 시간', null=True)),
                ('owner', models.ForeignKey(db_comment='스케쥴 소유자', help_text='스케쥴 소유자', on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('group', models.ForeignKey(db_comment='스케쥴 그룹', help_text='스케쥴 그룹', on_delete=django.db.models.deletion.PROTECT, related_name='events', to='schedule.eventgroup', verbose_name='Group')),
            ],
            options={
                'db_table': 'schedule_event',
                'db_table_comment': '이벤트',
                'ordering': ['owner', 'type', 'start_time'],
                'unique_together': {('owner', 'uuid')},
            },
        ),
    ]
