# Generated by Django 5.1.1 on 2025-02-07 14:57

import caldal.util.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventgroup',
            name='is_default',
        ),
        migrations.AlterField(
            model_name='eventgroup',
            name='order_index',
            field=caldal.util.fields.OrderIndexField(blank=True, db_comment='순서를 정할 때 쓰는 값. 0이면 디폴트', db_index=True, default=0, help_text='순서를 정할 때 쓰는 값. 0이면 디폴트'),
        ),
    ]
