from django.utils.translation import gettext_lazy as _

SCHEDULE_TITLE_MAX_LENGTH = 200
SCHEDULE_GROUP_NAME_MAX_LENGTH = 100
DEFAULT_SCHEDULE_GROUP_COLOR_CODE = "#34C759"
DEFAULT_SCHEDULE_GROUP_NAME = _("기본")
SCHEDULE_TIMEZONE_MAX_LENGTH = 35
DEFAULT_TIMEZONE = "Asia/Seoul"
