from django.utils.translation import gettext_lazy as _

EVENT_TITLE_MAX_LENGTH = 200
EVENT_GROUP_NAME_MAX_LENGTH = 100
DEFAULT_SCHEDULE_GROUP_COLOR_CODE = "#34C759"
DEFAULT_SCHEDULE_GROUP_NAME = _("기본")
TIMEZONE_MAX_LENGTH = 35
DEFAULT_TIMEZONE = "Asia/Seoul"
EVENT_TYPE_MAX_LENGTH = 10
