services:
  db:
    image: postgres:17-bookworm
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - prod.env
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5441:5432"
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8011:8000"
    depends_on:
      - db
    env_file:
      - prod.env
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
volumes:
  db_data:
